### ISSUE TITLE
Querying cetaceans sightings in ESAS (Seabirds at Sea)

### ISSUE THREAD

**Issue by neil-ices-dk** [ices-eg/WGJCDP-Cetaceans#266]
Initial discussion:
- keep governance separate i.e. ESAS data should stay within that portal
- there is a technical possibility to do this (query ESAS data from the JCDP portal) using the same micro service method we already have on data.ices.dk
- longer term WGJCDP could discuss with JWGBIRD on harmonization and alignment
- Inventory: clearly delineated between JCDP and ESAS data

**Comment by neil-ices-dk** [comment]
this would be something that is realistic to move forward in 2023 as ESAS will not be finalised until late Autumn 2022

**Comment by NikiClear** [comment]
Pull in all cetacean species from ESAS.

**Comment by cmspinto** [comment]
Summary of Records in ESAS:




WormsAphiaID | InfraOrder | NoRecs | SpeciesEnglishName | SpeciesScientificName | DataAccess
-- | -- | -- | -- | -- | --
136980 | Cetacea | 96 | patterned dolphin |   | Public
136980 | Cetacea | 877 | unidentified dolphin |   | Public
136980 | Cetacea | 9 | unpatterned dolphin |   | Public
137013 | Cetacea | 107 | unidentified large Baleanoptera sp. |   | Public
2688 | Cetacea | 6 | Sei / Minke / Bottlenosed Whale |   | Public
2688 | Cetacea | 73 | unidentified large whale |   | Public
2688 | Cetacea | 3 | unidentified large whale with distinct dorsal fin |   | Public
2688 | Cetacea | 38 | unidentified medium whale |   | Public
2688 | Cetacea | 8 | unidentified medium whale with large fin |   | Public
2688 | Cetacea | 140 | unidentified small whale |   | Public
2688 | Cetacea | 95 | unidentified whale |   | Public
2688 | Cetacea | 139 | unidentified whale or dolphin |   | Public
137087 | Cetacea | 1369 | Minke Whale | Balaenoptera acutorostrata | Public
137088 | Cetacea | 69 | Sei Whale | Balaenoptera borealis | Public
137089 | Cetacea | 19 | Bryde's Whale | Balaenoptera edeni | Public
137090 | Cetacea | 7 | Blue Whale | Balaenoptera musculus | Public
137091 | Cetacea | 224 | Fin Whale | Balaenoptera physalus | Public
137115 | Cetacea | 3 | Beluga | Delphinapterus leucas | Public
137094 | Cetacea | 2259 | Common Dolphin | Delphinus delphis | Public
136980 | Cetacea | 1 | Common / Striped Dolphin | Delphinus delphis / Stenella coeruleoalba | Public
220222 | Cetacea | 1 | Northern Right Whale | Eubalaena australis | Public
137096 | Cetacea | 40 | Short-finned Pilot Whale | Globicephala macrorhynchus | Public
137097 | Cetacea | 618 | Long-finned Pilot Whale | Globicephala melas | Public
137017 | Cetacea | 19 | unidentified pilot whale | Globicephala sp. | Public
136980 | Cetacea | 4 | Pilot / False Killer Whale | Globicephala sp. / Pseudorca sp. | Public
137098 | Cetacea | 174 | Risso's Dolphin | Grampus griseus | Public
343899 | Cetacea | 48 | Northern Bottlenose Whale | Hyperoodon ampullatus | Public
137100 | Cetacea | 749 | Atlantic White-sided Dolphin | Lagenorhynchus acutus | Public
137101 | Cetacea | 2176 | White-beaked Dolphin | Lagenorhynchus albirostris | Public
137020 | Cetacea | 101 |   | Lagenorhynchus sp. | Public
137092 | Cetacea | 13 | Humpback Whale | Megaptera novaeangliae | Public
137121 | Cetacea | 5 | Sowerby's Beaked Whale | Mesoplodon bidens | Public
137122 | Cetacea | 3 | Blainville's Beaked Whale | Mesoplodon densirostris | Public
137126 | Cetacea | 2 | True's Beaked Whale | Mesoplodon mirus | Public
137034 | Cetacea | 35 | unidentified beaked whale | Mesoplodon sp. | Public
137102 | Cetacea | 240 | Killer Whale | Orcinus orca | Public
137117 | Cetacea | 12230 | Harbour Porpoise | Phocoena phocoena | Public
137119 | Cetacea | 218 | Sperm Whale | Physeter macrocephalus | Public
137104 | Cetacea | 9 | False Killer Whale | Pseudorca crassidens | Public
254970 | Cetacea | 1 | Atlantic Hump-backed Dolphin | Souza teuszii | Public
137107 | Cetacea | 176 | Striped Dolphin | Stenella coeruleoalba | Public
137108 | Cetacea | 209 | Atlantic Spotted Dolphin | Stenella frontalis | Public
137111 | Cetacea | 389 | Bottlenose Dolphin | Tursiops truncatus | Public
137127 | Cetacea | 5 | Cuvier's Beaked Whale | Ziphius cavirostris | Public
2688 | Cetacea | 1 | unidentified whale |   | Restricted
136980 | Cetacea | 12 | unidentified dolphin |  | Restricted
137087 | Cetacea | 5 | Minke Whale | Balaenoptera acutorostrata | Restricted
137094 | Cetacea | 3 | Common Dolphin | Delphinus delphis | Restricted
343899 | Cetacea | 1 | Northern Bottlenose Whale | Hyperoodon ampullatus | Restricted
137100 | Cetacea | 3 | Atlantic White-sided Dolphin | Lagenorhynchus acutus | Restricted
137101 | Cetacea | 73 | White-beaked Dolphin | Lagenorhynchus albirostris | Restricted
137020 | Cetacea | 1 |   | Lagenorhynchus sp. | Restricted
137117 | Cetacea | 6822 | Harbour Porpoise | Phocoena phocoena | Restricted
137119 | Cetacea | 1 | Sperm Whale | Physeter macrocephalus | Restricted
137111 | Cetacea | 10 | Bottlenose Dolphin | Tursiops truncatus | Restricted

We have to contact ESAS and think about how to link these two datasets.

**Comment by cmspinto** [comment]
@mehdiabbasi  will add a layer to the map with the ESAS data. 
This also means that we will have to add some kind of legend.

**Comment by NikkiTaylorJNCC** [comment]
@cmspinto Assume this will happen in the new year after we have properly discussed plans with the ESAS WGJBIRD?

**Comment by neil-ices-dk** [comment]
> @cmspinto Assume this will happen in the new year after we have properly discussed plans with the ESAS WGJBIRD?

i agree - we are not quite there yet (from a governance perspective); i would have thought it will be part of the Feb '23 meeting with the ESAS/Bird group so that they are onboard with this.

**Comment by cmspinto** [comment]
We have now an idea of what to do. Need to talk with @mehdiabbasi  how will be the best way to implement it. 

Map stays as it is:
![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/5900c9d3-051c-463a-ab59-ccaa744b1444)


Hoover legend will be updated to include the ESAS observations:
![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/65db6d7f-8e5f-4dd0-9bd2-1bd570c73d93)

Proposal:
Number of observations (JCDP): 3
Number of observations (ESAS): 2
Number of surveys (JCDP): 2
Number of surveys (ESAS): 1



Filter will also include a toggle button  to enable or disable JCDP or ESAS datasets:
![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/81179a59-770e-430d-9bb8-a2a11f3cbb32)


The download summary will be changed to show the ESAS public data.

The download will include two zip files, one wiht the data form JCDP and another one with the cetaceans open data from ESAS.

**Comment by cmspinto** [comment]
We agree that the SP will return both:

![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/169825f3-0dc4-4489-851a-8fe22efea719)

The legend in case both (JCDP and ESAS) are on is based on the yellow.

**Comment by NikiClear** [comment]
Thanks Carlos. 
I think it does make sense to have species count return from both, and keep survey count separate. 
We just need to make sure this is explained somewhere on the map legend or webpage so users know what these numbers are.

**Comment by cmspinto** [comment]
Does it look fine like this before downloading the data:

![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/8b1e88d9-997d-4e9b-a970-0e4b1a80d4c1)


**Note:** This is the original columns in the inventory of ESAS

**Comment by cmspinto** [comment]
This would be how the download looks:

![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/8705477/d74b2306-887a-4303-857b-a6719bb8c89a)

**Comment by mehdiabbasi** [comment]
Hi All,

View on map beta version is ready for your review [https://cetaceans.ices.dk/beta/viewonmap](https://cetaceans.ices.dk/beta/viewonmap) including option to select ESAS or JCDP

**Comment by NikkiTaylorJNCC** [comment]
> Does it look fine like this before downloading the data:
> 
> ![image](https://private-user-images.githubusercontent.com/8705477/333602311-8b1e88d9-997d-4e9b-a970-0e4b1a80d4c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzA1MzUsIm5iZiI6MTcxODI3MDIzNSwicGF0aCI6Ii84NzA1NDc3LzMzMzYwMjMxMS04YjFlODhkOS05OTdkLTRlOWItYTk3MC0wZTRiMWE4MGQ0YzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTNUMDkxNzE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWNkNDFmZDIwNTEyMGE0MDhlNDY1Mzk1MWJkMGJjMmIwMDg2OTYzMDAxY2VhNjhjNWNmY2Q1MmYyYTJhYjY0YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3iZK7uRqNpdAXOv16D6-G-8-AaGE3S8bYwgu-TqhBe8)
> 
> **Note:** This is the original columns in the inventory of ESAS

Hi @cmspinto could we add 'the' - there are *** campaigns in **THE** ESAS database. Thanks :)

**Comment by NikkiTaylorJNCC** [comment]
> Hi All,
> 
> View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP

Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?

**Comment by mehdiabbasi** [comment]
> > Hi All,
> > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> 
> Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?

@NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon 
![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/38282276/13cd3f70-1f11-46dc-b854-04256432d9d5)

**Comment by NikkiTaylorJNCC** [comment]
> > > Hi All,
> > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > 
> > 
> > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> 
> @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)

When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...

**Comment by mehdiabbasi** [comment]
> > > > Hi All,
> > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > 
> > > 
> > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > 
> > 
> > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> 
> When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...

I fixed the download link, it should work now. please try it again?

**Comment by mehdiabbasi** [comment]
> > > > > Hi All,
> > > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > > 
> > > > 
> > > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > > 
> > > 
> > > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> > 
> > 
> > When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...
> 
> I fixed the download link, it should work now. please try it again?

I can see there is an issue in download page that not apply ESAS or JCDP filter, @cmspinto  could you please apply filter on download page. ?selecteddataset=JCDP&selecteddataset=ESAS

**Comment by NikkiTaylorJNCC** [comment]
> > > > > > Hi All,
> > > > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > > > 
> > > > > 
> > > > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > > > 
> > > > 
> > > > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> > > 
> > > 
> > > When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...
> > 
> > 
> > I fixed the download link, it should work now. please try it again?
> 
> I can see there is an issue in download page that not apply ESAS or JCDP filter, @cmspinto could you please apply filter on download page. ?selecteddataset=JCDP&selecteddataset=ESAS

I de-seleted JCDP and updated the map to only show ESAS - drew one polygon around Svalbard, no records to download; drew another around the UK and it returned JCDP surveys...

![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/73958396/7163ef76-2aa4-4c34-ba97-0f58281ed222)

**Comment by mehdiabbasi** [comment]
> > > > > > > Hi All,
> > > > > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > > > > 
> > > > > > 
> > > > > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > > > > 
> > > > > 
> > > > > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> > > > 
> > > > 
> > > > When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...
> > > 
> > > 
> > > I fixed the download link, it should work now. please try it again?
> > 
> > 
> > I can see there is an issue in download page that not apply ESAS or JCDP filter, @cmspinto could you please apply filter on download page. ?selecteddataset=JCDP&selecteddataset=ESAS
> 
> I de-seleted JCDP and updated the map to only show ESAS - drew one polygon around Svalbard, no records to download; drew another around the UK and it returned JCDP surveys...
> 
> ![image](https://private-user-images.githubusercontent.com/73958396/339325660-7163ef76-2aa4-4c34-ba97-0f58281ed222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzU3NzUsIm5iZiI6MTcxODI3NTQ3NSwicGF0aCI6Ii83Mzk1ODM5Ni8zMzkzMjU2NjAtNzE2M2VmNzYtMmFhNC00YzM0LWJhOTctMGY1ODI4MWVkMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwNDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZjRkNjg5N2RmYjQ1YTA3NDY5NDBmNWVhM2ZmOWQ4ZDg4MzQwYjZhYjdlMzVhYTdlMDYyZTZmNTNlNDhkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZdEqWSBBJVP84njjV5KN9gqK_0wK0jMPL4VjvckN7U)

I try to reproduce the map following your steps, it is working here unless I missed any steps. Which browser do you use, Could you please try press Ctrl + F5 and try again?
![image](https://github.com/ices-eg/WGJCDP-Cetaceans/assets/38282276/87b4d1e5-45ec-460a-94ee-65e52f2348fe)

**Comment by NikkiTaylorJNCC** [comment]
> > > > > > > > Hi All,
> > > > > > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > > > > > 
> > > > > > > 
> > > > > > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > > > > > 
> > > > > > 
> > > > > > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> > > > > 
> > > > > 
> > > > > When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...
> > > > 
> > > > 
> > > > I fixed the download link, it should work now. please try it again?
> > > 
> > > 
> > > I can see there is an issue in download page that not apply ESAS or JCDP filter, @cmspinto could you please apply filter on download page. ?selecteddataset=JCDP&selecteddataset=ESAS
> > 
> > 
> > I de-seleted JCDP and updated the map to only show ESAS - drew one polygon around Svalbard, no records to download; drew another around the UK and it returned JCDP surveys...
> > ![image](https://private-user-images.githubusercontent.com/73958396/339325660-7163ef76-2aa4-4c34-ba97-0f58281ed222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzU3NzUsIm5iZiI6MTcxODI3NTQ3NSwicGF0aCI6Ii83Mzk1ODM5Ni8zMzkzMjU2NjAtNzE2M2VmNzYtMmFhNC00YzM0LWJhOTctMGY1ODI4MWVkMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwNDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZjRkNjg5N2RmYjQ1YTA3NDY5NDBmNWVhM2ZmOWQ4ZDg4MzQwYjZhYjdlMzVhYTdlMDYyZTZmNTNlNDhkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZdEqWSBBJVP84njjV5KN9gqK_0wK0jMPL4VjvckN7U)
> 
> I try to reproduce the map following your steps, it is working here unless I missed any steps. Which browser do you use, Could you please try press Ctrl + F5 and try again? ![image](https://private-user-images.githubusercontent.com/38282276/339330523-87b4d1e5-45ec-460a-94ee-65e52f2348fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTE2NjksIm5iZiI6MTcxODM1MTM2OSwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMzA1MjMtODdiNGQxZTUtNDVlYy00NjBhLTk0ZWUtNjVlNTJmMjM0OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA3NDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmFjZmYwMmNmN2FmNjc5YTQ1ZDNmOGM3ZjUwZDRkM2Y4ZWRhMzE1ZDI1MzY3OTBmOTk0ZWMxZjZmNGY2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S4_5L8e7vVsugkXlKfMqZuklOGcmgS1KT-33um9oG_Y)

I'm still having the same issue - tried Chrome and Edge, ctrl F5 - I deselect JCDP data, update the map, draw a polygon where I know there is only ESAS data - no data to download, I draw a polygon where there is JCDP data and it returns all the JCDP data in teh download but no sign of ESAS data...I'll see if Niki can have a play next week as well, see if she's having the same issue.

**Comment by NikkiTaylorJNCC** [comment]
> > > > > > > > > Hi All,
> > > > > > > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > > > > > > 
> > > > > > > 
> > > > > > > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> > > > > > 
> > > > > > 
> > > > > > When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...
> > > > > 
> > > > > 
> > > > > I fixed the download link, it should work now. please try it again?
> > > > 
> > > > 
> > > > I can see there is an issue in download page that not apply ESAS or JCDP filter, @cmspinto could you please apply filter on download page. ?selecteddataset=JCDP&selecteddataset=ESAS
> > > 
> > > 
> > > I de-seleted JCDP and updated the map to only show ESAS - drew one polygon around Svalbard, no records to download; drew another around the UK and it returned JCDP surveys...
> > > ![image](https://private-user-images.githubusercontent.com/73958396/339325660-7163ef76-2aa4-4c34-ba97-0f58281ed222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzU3NzUsIm5iZiI6MTcxODI3NTQ3NSwicGF0aCI6Ii83Mzk1ODM5Ni8zMzkzMjU2NjAtNzE2M2VmNzYtMmFhNC00YzM0LWJhOTctMGY1ODI4MWVkMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwNDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZjRkNjg5N2RmYjQ1YTA3NDY5NDBmNWVhM2ZmOWQ4ZDg4MzQwYjZhYjdlMzVhYTdlMDYyZTZmNTNlNDhkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZdEqWSBBJVP84njjV5KN9gqK_0wK0jMPL4VjvckN7U)
> > 
> > 
> > I try to reproduce the map following your steps, it is working here unless I missed any steps. Which browser do you use, Could you please try press Ctrl + F5 and try again? ![image](https://private-user-images.githubusercontent.com/38282276/339330523-87b4d1e5-45ec-460a-94ee-65e52f2348fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTE2NjksIm5iZiI6MTcxODM1MTM2OSwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMzA1MjMtODdiNGQxZTUtNDVlYy00NjBhLTk0ZWUtNjVlNTJmMjM0OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA3NDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmFjZmYwMmNmN2FmNjc5YTQ1ZDNmOGM3ZjUwZDRkM2Y4ZWRhMzE1ZDI1MzY3OTBmOTk0ZWMxZjZmNGY2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S4_5L8e7vVsugkXlKfMqZuklOGcmgS1KT-33um9oG_Y)
> 
> I'm still having the same issue - tried Chrome and Edge, ctrl F5 - I deselect JCDP data, update the map, draw a polygon where I know there is only ESAS data - no data to download, I draw a polygon where there is JCDP data and it returns all the JCDP data in teh download but no sign of ESAS data...I'll see if Niki can have a play next week as well, see if she's having the same issue.

Hi @mehdiabbasi the option to filter JCDP/ESAS data has now disappeared altogether from the beta link.

**Comment by mehdiabbasi** [comment]
> > > > > > > > > > Hi All,
> > > > > > > > > > View on map beta version is ready for your review https://cetaceans.ices.dk/beta/viewonmap including option to select ESAS or JCDP
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > Looks great, thanks Mehdi! I can't select ESAS records via the polygon tool, is because this is in beta? Also wondering if there's a way to give a little more detail to users on JCDP V ESAS data - is it possible to add alt text when you hover over the select boxes and text for the two options, and add in a brief line that way? Otherwise maybe a short line of text at the top of left of the map view?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @NikkiTaylorJNCC What is wrong with ESAS and polygon? I can filter them with polygon ![image](https://private-user-images.githubusercontent.com/38282276/339321271-13cd3f70-1f11-46dc-b854-04256432d9d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzQzODQsIm5iZiI6MTcxODI3NDA4NCwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMjEyNzEtMTNjZDNmNzAtMWYxMS00NmRjLWI4NTQtMDQyNTY0MzJkOWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwMjEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0ZmRjOWM0ZDI4Nzc5ZjJlZDE2NWE0NzBhMWFmZGIyZmI5OGY2MjA5OWExYzgwOTZlMzM5NTUyYzQ3NDkyMjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q5JfWWaOVG6Go1hYQF6ezb7kpN3bTCeZx_zdqu6XbJU)
> > > > > > > 
> > > > > > > 
> > > > > > > When I try to download the selection from the polygon, it says 'no data in your selection for ESAS data...
> > > > > > 
> > > > > > 
> > > > > > I fixed the download link, it should work now. please try it again?
> > > > > 
> > > > > 
> > > > > I can see there is an issue in download page that not apply ESAS or JCDP filter, @cmspinto could you please apply filter on download page. ?selecteddataset=JCDP&selecteddataset=ESAS
> > > > 
> > > > 
> > > > I de-seleted JCDP and updated the map to only show ESAS - drew one polygon around Svalbard, no records to download; drew another around the UK and it returned JCDP surveys...
> > > > ![image](https://private-user-images.githubusercontent.com/73958396/339325660-7163ef76-2aa4-4c34-ba97-0f58281ed222.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzU3NzUsIm5iZiI6MTcxODI3NTQ3NSwicGF0aCI6Ii83Mzk1ODM5Ni8zMzkzMjU2NjAtNzE2M2VmNzYtMmFhNC00YzM0LWJhOTctMGY1ODI4MWVkMjIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDEwNDQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZjRkNjg5N2RmYjQ1YTA3NDY5NDBmNWVhM2ZmOWQ4ZDg4MzQwYjZhYjdlMzVhYTdlMDYyZTZmNTNlNDhkMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SZdEqWSBBJVP84njjV5KN9gqK_0wK0jMPL4VjvckN7U)
> > > 
> > > 
> > > I try to reproduce the map following your steps, it is working here unless I missed any steps. Which browser do you use, Could you please try press Ctrl + F5 and try again? ![image](https://private-user-images.githubusercontent.com/38282276/339330523-87b4d1e5-45ec-460a-94ee-65e52f2348fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNTE2NjksIm5iZiI6MTcxODM1MTM2OSwicGF0aCI6Ii8zODI4MjI3Ni8zMzkzMzA1MjMtODdiNGQxZTUtNDVlYy00NjBhLTk0ZWUtNjVlNTJmMjM0OGZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE0VDA3NDkyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0YmFjZmYwMmNmN2FmNjc5YTQ1ZDNmOGM3ZjUwZDRkM2Y4ZWRhMzE1ZDI1MzY3OTBmOTk0ZWMxZjZmNGY2MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S4_5L8e7vVsugkXlKfMqZuklOGcmgS1KT-33um9oG_Y)
> > 
> > 
> > I'm still having the same issue - tried Chrome and Edge, ctrl F5 - I deselect JCDP data, update the map, draw a polygon where I know there is only ESAS data - no data to download, I draw a polygon where there is JCDP data and it returns all the JCDP data in teh download but no sign of ESAS data...I'll see if Niki can have a play next week as well, see if she's having the same issue.
> 
> Hi @mehdiabbasi the option to filter JCDP/ESAS data has now disappeared altogether from the beta link.

Hi @NikkiTaylorJNCC, sorry for that, It is fixed now. @cmspinto Could you please test the scenario that NikKi provided above, to see if you see also wrong map?

**Comment by NikkiTaylorJNCC** [comment]
Complete?
